GET http://localhost:3000/documents
Content-Type: application/json

###

POST http://localhost:3000/documents/user
Content-Type: application/json

{
    "userName": "Dante"
}

###

POST http://localhost:3000/documents/add
Content-Type: application/json

{
    "newDocumentTitle": "Fredag",
    "newDocumentContent": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "userId": 1
}

###

PUT http://localhost:3000/documents/6
Content-Type: application/json

{
    "updatedContent": "Snart är det påskafton"
}
